Improve BitBucket unauthorized error message (#813)
* Improve BitBucket unauthorized error message

On 401 unauthorized responses, BitBucket does not always return a JSON
body. That was causing the error handling code that's being changed here
to throw an error itself, which led to errors like:

```
error: invalid json response body at [url] reason: Unexpected end of JSON input {"type":"invalid-json"}
```

Which was a bit confusing to me. This commit changes the error handling
code to return a generic error message instead. So with an incorrect
BitBucket token, CML now prints:

```
error: Unauthorized
```

Which should be more helpful to the user.

* Fix error handling logic

Co-authored-by: Helio Machado <0x2b3bfa0+git@googlemail.com>

Co-authored-by: Helio Machado <0x2b3bfa0+git@googlemail.com>